services:
  db:
    image: postgres:15.2
    volumes:
      - project-mentoring-db:/var/lib/postgresql/data
    env_file:
      - envs/dev/.env.db

  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project-mentoring
    ports:
      - "8000:8000"
    env_file:
      - envs/dev/.env.be
    depends_on:
      - db

volumes:
  project-mentoring-db:
    external: true