# Generated by Django 4.2 on 2023-04-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mentorship',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
